% Auto-generated by cameraCalibrator app on 29-Apr-2024
%-------------------------------------------------------
function cameraParams=calibrateCamera()

% Define images to process
imageFileNames = {'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard1.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard2.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard3.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard4.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard6.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard9.jpg',...
'D:\Academic docs\Spring 24\Computer Vision\Assignment 3\Pics\checkerboard10.jpg',...
};
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
end